### ISSUE TITLE
Breaking a block that drops XP with a tool enchanted with both Mending and Telekinesis causes the game to crash in an infinite loop

### ISSUE THREAD

**Issue by f-raZ0R** [btwonion/telekinesis#17]
server log:

[16:49:48] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.StackOverflowError: null
	at java.util.HashMap.hash(HashMap.java:338) ~[?:?]
	at java.util.HashMap.getNode(HashMap.java:568) ~[?:?]
	at java.util.HashMap.get(HashMap.java:556) ~[?:?]
	at net.minecraft.class_2487.method_10540(class_2487.java:279) ~[client-intermediary.jar:?]
	at net.minecraft.class_2487.method_10554(class_2487.java:418) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799.method_7921(class_1799.java:560) ~[client-intermediary.jar:?]
	at net.minecraft.class_1890.method_8225(class_1890.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.class_1890.method_24365(class_1890.java:289) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:258) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_1303.method_35051(class_1303.java:265) ~[client-intermediary.jar:?]
{etc}

**Comment by f-raZ0R** [comment]
Also on 1.20.1

**Comment by btwonion** [comment]
Thanks for the report!
